services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www
            # Use delegated para melhor performance, excluindo diretórios problemáticos
            - /var/www/vendor/
            - /var/www/node_modules/
        depends_on:
            - db
    web:
        image: nginx:alpine
        ports:
            - "8080:80" # - "80:80"
        volumes:
            - ./:/var/www:cached
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: concrettec_db
            MYSQL_USER: concrettec_user
            MYSQL_PASSWORD: secret
        ports:
            - "3307:3306"   # ou "3306:3306", se preferir, conforme já conversamos
        volumes:
            - dbdata:/var/lib/mysql
volumes:
    dbdata:
