<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use function Laravel\Prompts\select;

class Construction extends Model
{
    protected $fillable = [
        'name', 'enterprise_id', 'address_id',
    ];

    public function enterprise(): BelongsTo
    {
        return $this->belongsTo(Enterprise::class);
    }

    public function address(): BelongsTo
    {
        return $this->belongsTo(Address::class);
    }
    protected static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub
        static::addGlobalScope('agencia', function (Builder $builder)  {
            if(auth()->user() && !is_null(auth()->user()?->enterprise_id)){
                $builder->where('constructions.enterprise_id', auth()->user()->enterprise_id);
            }
        });
    }
}
